mysql:
  dns: root:123@tcp(127.0.0.1:3306)/ttms?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "127.0.0.1:6379"
  DB: 0
  poolSize: 30
  minIdleConn: 30
qiniu:
  Scope: "zsy-ttms"
  QiniuAK: "C5IdEtxZFLx0oS9iY8C1yrS6rLYnfzB4XV8rt4HU"
  QiniuSk: "MpTfRFklA1fWfmym2YhSxebykuxmi6SoBCFOd1Y4"
jwt:
  AKey: "zsy_Akey"
  RKey: "zsy_Rkey"
  Timeout: 300
  MaxRefresh: 86400